// Copyright (c) 2025 by Marko Gaćeša

package scene

import (
	"github.com/go-gl/glfw/v3.3/glfw"

	"github.com/marko-gacesa/gamatet/graphics/render"
	"github.com/marko-gacesa/gamatet/internal/config/key"
	. "github.com/marko-gacesa/gamatet/internal/i18n"
)

const (
	HUDPosFPS       = render.HUDUpperRight
	HUDPosLatencies = render.HUDUpperLeft
)

var KeyMap = map[key.Key]glfw.Key{
	key.Unknown:      glfw.KeyUnknown,
	key.Space:        glfw.KeySpace,
	key.Apostrophe:   glfw.KeyApostrophe,
	key.Comma:        glfw.KeyComma,
	key.Minus:        glfw.KeyMinus,
	key.Period:       glfw.KeyPeriod,
	key.Slash:        glfw.KeySlash,
	key.N0:           glfw.Key0,
	key.N1:           glfw.Key1,
	key.N2:           glfw.Key2,
	key.N3:           glfw.Key3,
	key.N4:           glfw.Key4,
	key.N5:           glfw.Key5,
	key.N6:           glfw.Key6,
	key.N7:           glfw.Key7,
	key.N8:           glfw.Key8,
	key.N9:           glfw.Key9,
	key.Semicolon:    glfw.KeySemicolon,
	key.Equal:        glfw.KeyEqual,
	key.A:            glfw.KeyA,
	key.B:            glfw.KeyB,
	key.C:            glfw.KeyC,
	key.D:            glfw.KeyD,
	key.E:            glfw.KeyE,
	key.F:            glfw.KeyF,
	key.G:            glfw.KeyG,
	key.H:            glfw.KeyH,
	key.I:            glfw.KeyI,
	key.J:            glfw.KeyJ,
	key.K:            glfw.KeyK,
	key.L:            glfw.KeyL,
	key.M:            glfw.KeyM,
	key.N:            glfw.KeyN,
	key.O:            glfw.KeyO,
	key.P:            glfw.KeyP,
	key.Q:            glfw.KeyQ,
	key.R:            glfw.KeyR,
	key.S:            glfw.KeyS,
	key.T:            glfw.KeyT,
	key.U:            glfw.KeyU,
	key.V:            glfw.KeyV,
	key.W:            glfw.KeyW,
	key.X:            glfw.KeyX,
	key.Y:            glfw.KeyY,
	key.Z:            glfw.KeyZ,
	key.LeftBracket:  glfw.KeyLeftBracket,
	key.Backslash:    glfw.KeyBackslash,
	key.RightBracket: glfw.KeyRightBracket,
	key.GraveAccent:  glfw.KeyGraveAccent,
	key.World1:       glfw.KeyWorld1,
	key.World2:       glfw.KeyWorld2,
	key.Escape:       glfw.KeyEscape,
	key.Enter:        glfw.KeyEnter,
	key.Tab:          glfw.KeyTab,
	key.Backspace:    glfw.KeyBackspace,
	key.Insert:       glfw.KeyInsert,
	key.Delete:       glfw.KeyDelete,
	key.Right:        glfw.KeyRight,
	key.Left:         glfw.KeyLeft,
	key.Down:         glfw.KeyDown,
	key.Up:           glfw.KeyUp,
	key.PageUp:       glfw.KeyPageUp,
	key.PageDown:     glfw.KeyPageDown,
	key.Home:         glfw.KeyHome,
	key.End:          glfw.KeyEnd,
	key.CapsLock:     glfw.KeyCapsLock,
	key.ScrollLock:   glfw.KeyScrollLock,
	key.NumLock:      glfw.KeyNumLock,
	key.PrintScreen:  glfw.KeyPrintScreen,
	key.Pause:        glfw.KeyPause,
	key.F1:           glfw.KeyF1,
	key.F2:           glfw.KeyF2,
	key.F3:           glfw.KeyF3,
	key.F4:           glfw.KeyF4,
	key.F5:           glfw.KeyF5,
	key.F6:           glfw.KeyF6,
	key.F7:           glfw.KeyF7,
	key.F8:           glfw.KeyF8,
	key.F9:           glfw.KeyF9,
	key.F10:          glfw.KeyF10,
	key.F11:          glfw.KeyF11,
	key.F12:          glfw.KeyF12,
	key.F13:          glfw.KeyF13,
	key.F14:          glfw.KeyF14,
	key.F15:          glfw.KeyF15,
	key.F16:          glfw.KeyF16,
	key.F17:          glfw.KeyF17,
	key.F18:          glfw.KeyF18,
	key.F19:          glfw.KeyF19,
	key.F20:          glfw.KeyF20,
	key.F21:          glfw.KeyF21,
	key.F22:          glfw.KeyF22,
	key.F23:          glfw.KeyF23,
	key.F24:          glfw.KeyF24,
	key.F25:          glfw.KeyF25,
	key.KP0:          glfw.KeyKP0,
	key.KP1:          glfw.KeyKP1,
	key.KP2:          glfw.KeyKP2,
	key.KP3:          glfw.KeyKP3,
	key.KP4:          glfw.KeyKP4,
	key.KP5:          glfw.KeyKP5,
	key.KP6:          glfw.KeyKP6,
	key.KP7:          glfw.KeyKP7,
	key.KP8:          glfw.KeyKP8,
	key.KP9:          glfw.KeyKP9,
	key.KPDecimal:    glfw.KeyKPDecimal,
	key.KPDivide:     glfw.KeyKPDivide,
	key.KPMultiply:   glfw.KeyKPMultiply,
	key.KPSubtract:   glfw.KeyKPSubtract,
	key.KPAdd:        glfw.KeyKPAdd,
	key.KPEnter:      glfw.KeyKPEnter,
	key.KPEqual:      glfw.KeyKPEqual,
	key.LeftShift:    glfw.KeyLeftShift,
	key.LeftControl:  glfw.KeyLeftControl,
	key.LeftAlt:      glfw.KeyLeftAlt,
	key.LeftSuper:    glfw.KeyLeftSuper,
	key.RightShift:   glfw.KeyRightShift,
	key.RightControl: glfw.KeyRightControl,
	key.RightAlt:     glfw.KeyRightAlt,
	key.RightSuper:   glfw.KeyRightSuper,
	key.Menu:         glfw.KeyMenu,
}

var KeyMapReverse = map[glfw.Key]key.Key{
	glfw.KeyUnknown:      key.Unknown,
	glfw.KeySpace:        key.Space,
	glfw.KeyApostrophe:   key.Apostrophe,
	glfw.KeyComma:        key.Comma,
	glfw.KeyMinus:        key.Minus,
	glfw.KeyPeriod:       key.Period,
	glfw.KeySlash:        key.Slash,
	glfw.Key0:            key.N0,
	glfw.Key1:            key.N1,
	glfw.Key2:            key.N2,
	glfw.Key3:            key.N3,
	glfw.Key4:            key.N4,
	glfw.Key5:            key.N5,
	glfw.Key6:            key.N6,
	glfw.Key7:            key.N7,
	glfw.Key8:            key.N8,
	glfw.Key9:            key.N9,
	glfw.KeySemicolon:    key.Semicolon,
	glfw.KeyEqual:        key.Equal,
	glfw.KeyA:            key.A,
	glfw.KeyB:            key.B,
	glfw.KeyC:            key.C,
	glfw.KeyD:            key.D,
	glfw.KeyE:            key.E,
	glfw.KeyF:            key.F,
	glfw.KeyG:            key.G,
	glfw.KeyH:            key.H,
	glfw.KeyI:            key.I,
	glfw.KeyJ:            key.J,
	glfw.KeyK:            key.K,
	glfw.KeyL:            key.L,
	glfw.KeyM:            key.M,
	glfw.KeyN:            key.N,
	glfw.KeyO:            key.O,
	glfw.KeyP:            key.P,
	glfw.KeyQ:            key.Q,
	glfw.KeyR:            key.R,
	glfw.KeyS:            key.S,
	glfw.KeyT:            key.T,
	glfw.KeyU:            key.U,
	glfw.KeyV:            key.V,
	glfw.KeyW:            key.W,
	glfw.KeyX:            key.X,
	glfw.KeyY:            key.Y,
	glfw.KeyZ:            key.Z,
	glfw.KeyLeftBracket:  key.LeftBracket,
	glfw.KeyBackslash:    key.Backslash,
	glfw.KeyRightBracket: key.RightBracket,
	glfw.KeyGraveAccent:  key.GraveAccent,
	glfw.KeyWorld1:       key.World1,
	glfw.KeyWorld2:       key.World2,
	glfw.KeyEscape:       key.Escape,
	glfw.KeyEnter:        key.Enter,
	glfw.KeyTab:          key.Tab,
	glfw.KeyBackspace:    key.Backspace,
	glfw.KeyInsert:       key.Insert,
	glfw.KeyDelete:       key.Delete,
	glfw.KeyRight:        key.Right,
	glfw.KeyLeft:         key.Left,
	glfw.KeyDown:         key.Down,
	glfw.KeyUp:           key.Up,
	glfw.KeyPageUp:       key.PageUp,
	glfw.KeyPageDown:     key.PageDown,
	glfw.KeyHome:         key.Home,
	glfw.KeyEnd:          key.End,
	glfw.KeyCapsLock:     key.CapsLock,
	glfw.KeyScrollLock:   key.ScrollLock,
	glfw.KeyNumLock:      key.NumLock,
	glfw.KeyPrintScreen:  key.PrintScreen,
	glfw.KeyPause:        key.Pause,
	glfw.KeyF1:           key.F1,
	glfw.KeyF2:           key.F2,
	glfw.KeyF3:           key.F3,
	glfw.KeyF4:           key.F4,
	glfw.KeyF5:           key.F5,
	glfw.KeyF6:           key.F6,
	glfw.KeyF7:           key.F7,
	glfw.KeyF8:           key.F8,
	glfw.KeyF9:           key.F9,
	glfw.KeyF10:          key.F10,
	glfw.KeyF11:          key.F11,
	glfw.KeyF12:          key.F12,
	glfw.KeyF13:          key.F13,
	glfw.KeyF14:          key.F14,
	glfw.KeyF15:          key.F15,
	glfw.KeyF16:          key.F16,
	glfw.KeyF17:          key.F17,
	glfw.KeyF18:          key.F18,
	glfw.KeyF19:          key.F19,
	glfw.KeyF20:          key.F20,
	glfw.KeyF21:          key.F21,
	glfw.KeyF22:          key.F22,
	glfw.KeyF23:          key.F23,
	glfw.KeyF24:          key.F24,
	glfw.KeyF25:          key.F25,
	glfw.KeyKP0:          key.KP0,
	glfw.KeyKP1:          key.KP1,
	glfw.KeyKP2:          key.KP2,
	glfw.KeyKP3:          key.KP3,
	glfw.KeyKP4:          key.KP4,
	glfw.KeyKP5:          key.KP5,
	glfw.KeyKP6:          key.KP6,
	glfw.KeyKP7:          key.KP7,
	glfw.KeyKP8:          key.KP8,
	glfw.KeyKP9:          key.KP9,
	glfw.KeyKPDecimal:    key.KPDecimal,
	glfw.KeyKPDivide:     key.KPDivide,
	glfw.KeyKPMultiply:   key.KPMultiply,
	glfw.KeyKPSubtract:   key.KPSubtract,
	glfw.KeyKPAdd:        key.KPAdd,
	glfw.KeyKPEnter:      key.KPEnter,
	glfw.KeyKPEqual:      key.KPEqual,
	glfw.KeyLeftShift:    key.LeftShift,
	glfw.KeyLeftControl:  key.LeftControl,
	glfw.KeyLeftAlt:      key.LeftAlt,
	glfw.KeyLeftSuper:    key.LeftSuper,
	glfw.KeyRightShift:   key.RightShift,
	glfw.KeyRightControl: key.RightControl,
	glfw.KeyRightAlt:     key.RightAlt,
	glfw.KeyRightSuper:   key.RightSuper,
	glfw.KeyMenu:         key.Menu,
}

func fieldStrings() render.FieldStrings {
	return render.FieldStrings{
		TitlePanel: struct {
			Score  string
			Blocks string
		}{
			Score:  T(KeyFieldTitlePanelScore),
			Blocks: T(KeyFieldTitlePanelBlocks),
		},
		SidePanel: struct {
			Player string
			Score  string
			Piece  string
			Next   string
		}{
			Player: T(KeyFieldSidePanelPlayer),
			Score:  T(KeyFieldSidePanelScore),
			Piece:  T(KeyFieldSidePanelPiece),
			Next:   T(KeyFieldSidePanelNext),
		},
		Message: struct {
			GameOver   string
			Victory    string
			Defeat     string
			Pause      string
			Suspended  string
			ServerLost string
		}{
			GameOver:   T(KeyFieldMessageGameOver),
			Victory:    T(KeyFieldMessageVictory),
			Defeat:     T(KeyFieldMessageDefeat),
			Pause:      T(KeyFieldMessagePause),
			Suspended:  T(KeyFieldMessageSuspended),
			ServerLost: T(KeyFieldMessageServerLost),
		},
	}
}
